version: '3.9'

services:
  backend:
    image: fastapi-test-server:latest
    ports:
      - "9090:8000"
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
